### PR TITLE
move to mdbook

### PR DESCRIPTION
**Pull request by svenefftinge**

### CODE REVIEW

**Comment by jbicker** [comment]
This border on focused elements is not necessary on these menu items. 
screen shot 2018-11-15 at 16 35 28

It is ok for the search field or a selected theme.

**Comment by jbicker** [comment]
The theme of the inline doc is initially Light instead Dark.
screen shot 2018-11-15 at 16 41 48

**Comment by jbicker** [comment]
The navigation through pages with left/right arrow keys is cool but in inline help after a new page was loaded the focus gets back to the url field. So it is not really useful there.

**Comment by svenefftinge** [comment]
The focus and the white background for the inline help needs to be fixed in theia.

**Pull request merged**
